/**
 * `DESIGNS`, read out of `@viliha/vui-core` at export time and written back as data.
 *
 * **Generated. Do not edit.** `node scripts/export-store.mjs <dir>` in the monorepo rewrites this
 * file, so a change made here is lost on the next sync. The designs are the product's, and the
 * storefront only reads them.
 */
export const DESIGNS = [
  {
    "id": "voilet",
    "label": "Voilet",
    "hint": "The standard: a full-height sidebar with the header beside it.",
    "tokens": {},
    "frame": {
      "shell": "voilet",
      "regions": [
        "identity",
        "sidebarTop",
        "sidebarNav",
        "search",
        "pageHeader",
        "children"
      ],
      "sidebarWidth": 290,
      "sidebarRailWidth": 90,
      "sidebarFill": "tinted",
      "headingCase": "sentence",
      "activeMark": "bar-tint",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "neon",
    "label": "Console",
    "hint": "A global bar with a context switcher, and a sidebar scoped to what it selects.",
    "tokens": {
      "--font-sans": "var(--font-inter), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "\"CommitMono\", ui-monospace, SFMono-Regular, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "14px",
      "--text-body-leading": "20px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.25rem",
      "--radius": "6px",
      "--vui-radius-surface": "8px",
      "--border-width": "1px",
      "--vui-control-h": "32px",
      "--vui-control-h-sm": "28px",
      "--vui-header-h": "64px",
      "--vui-header-h-lg": "64px",
      "--background": "#ffffff",
      "--foreground": "#262626",
      "--card": "#ffffff",
      "--card-foreground": "#262626",
      "--popover": "#ffffff",
      "--popover-foreground": "#262626",
      "--muted": "#f7f7f7",
      "--muted-foreground": "#525252",
      "--accent": "#ebebeb",
      "--accent-foreground": "#262626",
      "--border": "#cbcbcb",
      "--input": "#cbcbcb",
      "--ring": "#262626",
      "--sidebar": "#f7f7f7",
      "--sidebar-foreground": "#262626",
      "--sidebar-border": "#cbcbcb",
      "--sidebar-accent": "#ebebeb",
      "--vui-selected": "#ebebeb",
      "--vui-selected-foreground": "#262626",
      "--sidebar-accent-foreground": "#262626",
      "--brand": "#262626",
      "--primary": "#262626",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#262626",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#6f6f6f",
      "--success": "#39a57d",
      "--warning": "#ba7b23",
      "--info": "#1763a1",
      "--destructive": "#e62719",
      "--vui-table-cell-px": "16px",
      "--vui-table-cell-py": "8px",
      "--vui-table-cell-size": "14px",
      "--vui-table-cell-weight": "400",
      "--vui-table-cell-color": "#262626",
      "--vui-table-head-size": "14px",
      "--vui-table-head-weight": "600",
      "--vui-table-head-color": "#262626",
      "--vui-table-key-weight": "700",
      "--vui-table-key-color": "#262626",
      "--vui-table-rule": "#ebebeb",
      "--vui-nav-heading-size": "10px",
      "--vui-nav-heading-weight": "600",
      "--vui-nav-heading-tracking": "0.5px",
      "--vui-crumb-gap": "2px",
      "--vui-crumb-sep-weight": "300",
      "--vui-nav-rule-w": "2px",
      "--vui-crumb-sep-size": "33px",
      "--vui-crumb-sep-opacity": "0.15",
      "--vui-search-w": "250px",
      "--vui-radius-xs": "4px",
      "--vui-icon-muted": "#939393",
      "--vui-logo-h": "26px",
      "--vui-shadow-xs": "0 0 1px 0 #0000001a",
      "--vui-shadow-sm": "0 5px 2px 0 #00000003, 0 3px 2px 0 #0000000d, 0 1px 1px 0 #00000017, 0 0 1px 0 #0000001a",
      "--vui-shadow-md": "0 29px 12px 0 #00000003, 0 16px 10px 0 #0000000d, 0 7px 7px 0 #00000017, 0 2px 4px 0 #0000001a",
      "--vui-shadow-lg": "0 118px 47px 0 #00000003, 0 66px 40px 0 #0000000d, 0 29px 29px 0 #00000017, 0 7px 16px 0 #0000001a",
      "--vui-shadow-xl": "0 118px 47px 0 #00000003, 0 66px 40px 0 #0000000d, 0 29px 29px 0 #00000017, 0 7px 16px 0 #0000001a",
      "--shadow-1": "0 1px 3px 0 rgba(0, 0, 0, 0.05)",
      "--shadow-3": "0 4px 8px 0 rgba(26, 26, 26, 0.1)",
      "--chart-1": "#084577",
      "--chart-2": "#39a57d",
      "--chart-3": "#ba7b23",
      "--chart-4": "#ab54eb",
      "--chart-5": "#ff3621",
      "--secondary": "#f7f7f7",
      "--secondary-foreground": "#525252",
      "--success-foreground": "#ffffff",
      "--warning-foreground": "#ffffff",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#262626",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-ring": "#262626",
      "--vui-duration-fast": "0.18s",
      "--vui-duration-base": "0.25s",
      "--vui-duration-slow": "0.5s",
      "--vui-duration-ui": "0.25s",
      "--vui-ease": "ease",
      "--vui-ease-ui": "ease",
      "--vui-ease-panel": "ease",
      "--font-scale": "1",
      "--text-caption": "12px",
      "--text-caption-leading": "1.5",
      "--text-lead": "16px",
      "--text-lead-leading": "1.5",
      "--text-h4": "18px",
      "--text-h4-leading": "1.333",
      "--text-h3": "20px",
      "--text-h3-leading": "1.4",
      "--text-h2": "24px",
      "--text-h2-leading": "1.333",
      "--text-h1": "28px",
      "--text-h1-leading": "1.286",
      "--text-display": "36px",
      "--text-display-leading": "1.222",
      "--text-3xl": "24px",
      "--vui-section-sm": "40rem",
      "--vui-section-md": "48rem",
      "--vui-section-lg": "64rem",
      "--vui-section-xl": "80rem",
      "--vui-section-2xl": "90rem",
      "--section-y": "96px",
      "--section-y-tight": "64px",
      "--brand-ink": "#161616",
      "--brand-mist": "#f7f7f7",
      "--brand-indigo": "#2272b4",
      "--brand-violet": "#ab54eb",
      "--brand-mint": "#34d59a",
      "--brand-coral": "#ff5f46",
      "--accent-violet": "#c27af7",
      "--accent-pink": "#d7a5fc",
      "--vui-file-badge-doc": "#e62719",
      "--vui-file-badge-doc-light": "#ff9e94",
      "--vui-file-badge-doc-mid": "#bd2b26",
      "--vui-file-badge-doc-shade": "#99221e",
      "--vui-file-badge-sheet": "#37c38f",
      "--vui-file-badge-sheet-light": "#8adec4",
      "--vui-file-badge-sheet-mid": "#39a57d",
      "--vui-file-badge-sheet-shade": "#0c9271",
      "--vui-file-badge-ink": "#161616",
      "--vui-file-badge-paper": "#ffffff",
      "--vui-file-badge-raw": "#e62719",
      "--vui-folder-badge": "#ffab00",
      "--vui-folder-badge-light": "#ffcc66",
      "--vui-tile-mark-box": "40px",
      "--vui-page-inset": "32px",
      "--vui-page-top-gap": "32px"
    },
    "frame": {
      "shell": "neon",
      "regions": [
        "identity",
        "contextSwitch",
        "search",
        "utilities",
        "account",
        "sidebarNav",
        "sidebarFoot",
        "children"
      ],
      "sidebarWidth": 249,
      "sidebarRailWidth": 90,
      "sidebarRailInset": 24,
      "sidebarFill": "tinted",
      "headingCase": "uppercase",
      "activeMark": "flat-tint",
      "contentMaxWidth": 1280
    }
  },
  {
    "id": "workspace",
    "label": "Desk",
    "hint": "Several records open at once: a resizable rail, a command bar and closable tabs.",
    "tokens": {
      "--font-sans": "var(--font-inter), ui-sans-serif, system-ui, sans-serif",
      "--text-body": "14px",
      "--vui-table-cell-py": "6px",
      "--vui-table-bare-pad": "0px",
      "--vui-table-cell-px": "12px",
      "--vui-table-cell-size": "14px",
      "--vui-table-cell-weight": "500",
      "--spacing": "0.25rem",
      "--vui-control-h": "32px",
      "--vui-control-h-sm": "28px",
      "--vui-tabs-h": "calc(var(--vui-control-h) + 4px)",
      "--vui-header-h": "48px",
      "--vui-header-h-lg": "48px",
      "--vui-nav-row-h": "36px",
      "--vui-page-inset": "16px",
      "--vui-page-top-gap": "16px"
    },
    "frame": {
      "shell": "workspace",
      "regions": [
        "identity",
        "quickActions",
        "sidebarNav",
        "sidebarTop",
        "children"
      ],
      "sidebarWidth": 240,
      "sidebarRailWidth": 90,
      "sidebarResize": {
        "min": 200,
        "max": 420
      },
      "sidebarFill": "none",
      "headingCase": "sentence",
      "activeMark": "flat-tint",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "jira",
    "label": "Board",
    "hint": "A global bar, a sidebar scoped to the project it selects, and a nav the reader can drag.",
    "tokens": {
      "--font-sans": "\"Atlassian Sans\", ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "\"Atlassian Mono\", ui-monospace, SFMono-Regular, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "14px",
      "--text-body-leading": "20px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "653",
      "--font-weight-bold": "700",
      "--spacing": "0.25rem",
      "--radius": "4px",
      "--vui-radius-surface": "8px",
      "--border-width": "1px",
      "--vui-control-h": "32px",
      "--vui-control-h-sm": "24px",
      "--vui-header-h": "48px",
      "--vui-header-h-lg": "48px",
      "--background": "#ffffff",
      "--foreground": "#292a2e",
      "--card": "#ffffff",
      "--card-foreground": "#292a2e",
      "--popover": "#ffffff",
      "--popover-foreground": "#292a2e",
      "--muted": "#f8f8f8",
      "--muted-foreground": "#6b6e76",
      "--accent": "#e9f2fe",
      "--accent-foreground": "#1868db",
      "--border": "#dfe1e5",
      "--input": "#8c8f97",
      "--ring": "#4688ec",
      "--sidebar": "#f8f8f8",
      "--sidebar-foreground": "#292a2e",
      "--sidebar-border": "#dfe1e5",
      "--sidebar-accent": "#e9f2fe",
      "--vui-selected": "#e9f2fe",
      "--vui-selected-foreground": "#1868db",
      "--sidebar-accent-foreground": "#1868db",
      "--brand": "#1868db",
      "--primary": "#1868db",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#1868db",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#1558bc",
      "--success": "#4c6b1f",
      "--warning": "#9e4c00",
      "--info": "#1558bc",
      "--destructive": "#ae2e24",
      "--vui-table-cell-px": "16px",
      "--vui-table-cell-py": "8px",
      "--vui-table-cell-size": "14px",
      "--vui-table-cell-weight": "400",
      "--vui-table-cell-color": "#292a2e",
      "--vui-table-head-size": "12px",
      "--vui-table-head-weight": "653",
      "--vui-table-head-color": "#6b6e76",
      "--vui-table-key-weight": "653",
      "--vui-table-key-color": "#292a2e",
      "--vui-table-rule": "#dfe1e5",
      "--vui-nav-heading-size": "12px",
      "--vui-nav-heading-weight": "653",
      "--vui-nav-heading-tracking": "0",
      "--vui-crumb-gap": "4px",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "2px",
      "--vui-crumb-sep-size": "16px",
      "--vui-crumb-sep-opacity": "0.5",
      "--vui-search-w": "320px",
      "--vui-radius-xs": "2px",
      "--vui-icon-muted": "#6b6e76",
      "--vui-logo-h": "24px",
      "--vui-shadow-xs": "0px 1px 1px #1e1f2140, 0px 0px 1px #1e1f214f",
      "--vui-shadow-sm": "0px 1px 1px #1e1f2140, 0px 0px 1px #1e1f214f",
      "--vui-shadow-md": "0px 8px 12px #1e1f2126, 0px 0px 1px #1e1f214f",
      "--vui-shadow-lg": "0px 8px 12px #1e1f2126, 0px 0px 1px #1e1f214f",
      "--vui-shadow-xl": "0px 12px 24px #1e1f2126, 0px 0px 1px #1e1f214f",
      "--shadow-1": "0 1px 1px #1e1f2140, 0 0 1px #1e1f214f",
      "--shadow-3": "0 8px 12px #1e1f2126, 0 0 1px #1e1f214f",
      "--chart-1": "#357de8",
      "--chart-2": "#82b536",
      "--chart-3": "#bf63f3",
      "--chart-4": "#f68909",
      "--chart-5": "#1558bc",
      "--secondary": "#f8f8f8",
      "--secondary-foreground": "#505258",
      "--success-foreground": "#ffffff",
      "--warning-foreground": "#ffffff",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#1868db",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-ring": "#4688ec",
      "--vui-duration-fast": "0.18s",
      "--vui-duration-base": "0.25s",
      "--vui-duration-slow": "0.5s",
      "--vui-duration-ui": "0.25s",
      "--vui-ease": "ease",
      "--vui-ease-ui": "ease",
      "--vui-ease-panel": "ease",
      "--font-scale": "1",
      "--text-caption": "12px",
      "--text-caption-leading": "1.333",
      "--text-lead": "16px",
      "--text-lead-leading": "1.5",
      "--text-h4": "16px",
      "--text-h4-leading": "1.25",
      "--text-h3": "20px",
      "--text-h3-leading": "1.2",
      "--text-h2": "24px",
      "--text-h2-leading": "1.167",
      "--text-h1": "28px",
      "--text-h1-leading": "1.143",
      "--text-display": "32px",
      "--text-display-leading": "1.125",
      "--text-3xl": "28px",
      "--vui-section-sm": "40rem",
      "--vui-section-md": "48rem",
      "--vui-section-lg": "64rem",
      "--vui-section-xl": "80rem",
      "--vui-section-2xl": "90rem",
      "--section-y": "96px",
      "--section-y-tight": "64px",
      "--brand-ink": "#161616",
      "--brand-mist": "#f7f7f7",
      "--brand-indigo": "#2272b4",
      "--brand-violet": "#ab54eb",
      "--brand-mint": "#34d59a",
      "--brand-coral": "#ff5f46",
      "--accent-violet": "#c27af7",
      "--accent-pink": "#d7a5fc",
      "--vui-file-badge-doc": "#e62719",
      "--vui-file-badge-doc-light": "#ff9e94",
      "--vui-file-badge-doc-mid": "#bd2b26",
      "--vui-file-badge-doc-shade": "#99221e",
      "--vui-file-badge-sheet": "#37c38f",
      "--vui-file-badge-sheet-light": "#8adec4",
      "--vui-file-badge-sheet-mid": "#39a57d",
      "--vui-file-badge-sheet-shade": "#0c9271",
      "--vui-file-badge-ink": "#161616",
      "--vui-file-badge-paper": "#ffffff",
      "--vui-file-badge-raw": "#e62719",
      "--vui-folder-badge": "#ffab00",
      "--vui-folder-badge-light": "#ffcc66",
      "--vui-tile-mark-box": "32px",
      "--vui-page-inset": "16px",
      "--vui-page-top-gap": "16px"
    },
    "frame": {
      "shell": "jira",
      "regions": [
        "identity",
        "primaryNav",
        "primaryAction",
        "search",
        "utilities",
        "account",
        "contextHeader",
        "breadcrumb",
        "pageTitle",
        "pageToolbar",
        "children"
      ],
      "sidebarWidth": 320,
      "sidebarResize": {
        "min": 240,
        "max": 720
      },
      "sidebarRailWidth": 90,
      "sidebarRailInset": 16,
      "sidebarFill": "tinted",
      "headingCase": "sentence",
      "activeMark": "flat-tint",
      "contentMaxWidth": 1280
    }
  },
  {
    "id": "zoho",
    "label": "Suite",
    "hint": "A light application with a dark panel of grouped sections.",
    "tokens": {
      "--font-sans": "Roboto, ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "\"Roboto Mono\", ui-monospace, SFMono-Regular, monospace",
      "--text-xs": "10px",
      "--text-sm": "12px",
      "--text-base": "16px",
      "--text-body": "14px",
      "--text-body-leading": "20px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "500",
      "--font-weight-bold": "700",
      "--spacing": "0.25rem",
      "--radius": "3px",
      "--vui-radius-surface": "5px",
      "--border-width": "1px",
      "--vui-control-h": "28px",
      "--vui-control-h-sm": "24px",
      "--vui-header-h": "48px",
      "--vui-header-h-lg": "48px",
      "--background": "#ffffff",
      "--foreground": "#18191b",
      "--card": "#ffffff",
      "--card-foreground": "#18191b",
      "--popover": "#ffffff",
      "--popover-foreground": "#18191b",
      "--muted": "#f2f3f4",
      "--muted-foreground": "#878a92",
      "--accent": "#e8eef8",
      "--accent-foreground": "#2558bb",
      "--border": "#e4e5e7",
      "--input": "#e4e5e7",
      "--ring": "#2558bb",
      "--sidebar": "#242933",
      "--vui-org-trigger-h": "var(--vui-header-h)",
      "--vui-zoho-rail-idle": "#bcbec2",
      "--vui-zoho-rail-active": "#f2f3f4",
      "--vui-zoho-rail-tint": "#20242d",
      "--sidebar-foreground": "#ffffff",
      "--sidebar-border": "#343a47",
      "--sidebar-accent": "#343a47",
      "--vui-selected": "#e8eef8",
      "--vui-selected-foreground": "#2558bb",
      "--sidebar-accent-foreground": "#ffffff",
      "--brand": "#2558bb",
      "--primary": "#2c66dd",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#2558bb",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#1e4a9e",
      "--success": "#198019",
      "--warning": "#ac6602",
      "--info": "#2558bb",
      "--destructive": "#dd1616",
      "--vui-table-cell-px": "12px",
      "--vui-table-cell-py": "6px",
      "--vui-table-cell-size": "14px",
      "--vui-table-cell-weight": "400",
      "--vui-table-cell-color": "#18191b",
      "--vui-table-head-size": "12px",
      "--vui-table-head-weight": "500",
      "--vui-table-head-color": "#878a92",
      "--vui-table-key-weight": "500",
      "--vui-table-key-color": "#18191b",
      "--vui-table-rule": "#e4e5e7",
      "--vui-nav-heading-size": "10px",
      "--vui-nav-heading-weight": "500",
      "--vui-nav-heading-tracking": "0.2px",
      "--vui-crumb-gap": "4px",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "2px",
      "--vui-crumb-sep-size": "14px",
      "--vui-crumb-sep-opacity": "0.4",
      "--vui-search-w": "280px",
      "--vui-radius-xs": "3px",
      "--vui-icon-muted": "#878a92",
      "--vui-logo-h": "24px",
      "--vui-shadow-xs": "0 1px 2px rgba(36, 41, 51, 0.06)",
      "--vui-shadow-sm": "0 1px 3px rgba(36, 41, 51, 0.08)",
      "--vui-shadow-md": "0 4px 8px rgba(36, 41, 51, 0.10)",
      "--vui-shadow-lg": "0 8px 16px rgba(36, 41, 51, 0.12)",
      "--vui-shadow-xl": "0 16px 32px rgba(36, 41, 51, 0.14)",
      "--shadow-1": "0 1px 3px rgba(36, 41, 51, 0.08)",
      "--shadow-3": "0 4px 8px rgba(36, 41, 51, 0.10)",
      "--chart-1": "#2558bb",
      "--chart-2": "#198019",
      "--chart-3": "#ac6602",
      "--chart-4": "#7a4bb5",
      "--chart-5": "#0f8a8a",
      "--secondary": "#f2f3f4",
      "--secondary-foreground": "#55585e",
      "--success-foreground": "#ffffff",
      "--warning-foreground": "#ffffff",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#2558bb",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-ring": "#2558bb",
      "--vui-duration-fast": "0.18s",
      "--vui-duration-base": "0.25s",
      "--vui-duration-slow": "0.5s",
      "--vui-duration-ui": "0.25s",
      "--vui-ease": "ease",
      "--vui-ease-ui": "ease",
      "--vui-ease-panel": "ease",
      "--font-scale": "1",
      "--text-caption": "10px",
      "--text-caption-leading": "1.4",
      "--text-lead": "16px",
      "--text-lead-leading": "1.5",
      "--text-h4": "16px",
      "--text-h4-leading": "1.375",
      "--text-h3": "18px",
      "--text-h3-leading": "1.333",
      "--text-h2": "20px",
      "--text-h2-leading": "1.3",
      "--text-h1": "24px",
      "--text-h1-leading": "1.25",
      "--text-display": "28px",
      "--text-display-leading": "1.214",
      "--text-3xl": "24px",
      "--vui-section-sm": "40rem",
      "--vui-section-md": "48rem",
      "--vui-section-lg": "64rem",
      "--vui-section-xl": "80rem",
      "--vui-section-2xl": "90rem",
      "--section-y": "96px",
      "--section-y-tight": "64px",
      "--brand-ink": "#161616",
      "--brand-mist": "#f7f7f7",
      "--brand-indigo": "#2272b4",
      "--brand-violet": "#ab54eb",
      "--brand-mint": "#34d59a",
      "--brand-coral": "#ff5f46",
      "--accent-violet": "#c27af7",
      "--accent-pink": "#d7a5fc",
      "--vui-file-badge-doc": "#e62719",
      "--vui-file-badge-doc-light": "#ff9e94",
      "--vui-file-badge-doc-mid": "#bd2b26",
      "--vui-file-badge-doc-shade": "#99221e",
      "--vui-file-badge-sheet": "#37c38f",
      "--vui-file-badge-sheet-light": "#8adec4",
      "--vui-file-badge-sheet-mid": "#39a57d",
      "--vui-file-badge-sheet-shade": "#0c9271",
      "--vui-file-badge-ink": "#161616",
      "--vui-file-badge-paper": "#ffffff",
      "--vui-file-badge-raw": "#e62719",
      "--vui-folder-badge": "#ffab00",
      "--vui-folder-badge-light": "#ffcc66",
      "--vui-tile-mark-box": "36px",
      "--vui-page-inset": "20px",
      "--vui-page-top-gap": "20px"
    },
    "frame": {
      "shell": "zoho",
      "regions": [
        "identity",
        "sectionNav",
        "pageNav",
        "search",
        "quickActions",
        "utilities",
        "account",
        "children"
      ],
      "sidebarWidth": 250,
      "sidebarRailWidth": 90,
      "sidebarFill": "inverted",
      "headingCase": "uppercase",
      "activeMark": "bar-tint",
      "contentMaxWidth": 1026
    }
  },
  {
    "id": "rackwise",
    "label": "Rack",
    "hint": "Dense warehouse operations: a light full-height rail, black primary actions, 4px corners.",
    "tokens": {
      "--font-sans": "var(--font-inter), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "var(--font-jetbrains-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "1rem",
      "--text-body": "14px",
      "--text-body-leading": "17px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.18rem",
      "--radius": "4px",
      "--vui-radius-surface": "6px",
      "--border-width": "2px",
      "--vui-control-h": "32px",
      "--vui-control-h-sm": "28px",
      "--vui-header-h": "44px",
      "--vui-header-h-lg": "66px",
      "--background": "#ffffff",
      "--foreground": "#010101",
      "--card": "#ffffff",
      "--card-foreground": "#010101",
      "--popover": "#ffffff",
      "--popover-foreground": "#010101",
      "--muted": "#fafafa",
      "--muted-foreground": "#6e6e6e",
      "--accent": "#f1f1f1",
      "--accent-foreground": "#010101",
      "--border": "#efefef",
      "--input": "#e3e3e3",
      "--ring": "#010101",
      "--sidebar": "#fafafa",
      "--sidebar-foreground": "#010101",
      "--sidebar-border": "#efefef",
      "--sidebar-accent": "#ffffff",
      "--vui-selected": "var(--accent)",
      "--vui-selected-foreground": "var(--accent-foreground)",
      "--sidebar-accent-foreground": "#010101",
      "--brand": "#010101",
      "--primary": "#010101",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#010101",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#171717",
      "--success": "#33664d",
      "--warning": "#dc6803",
      "--info": "#0086c9",
      "--destructive": "#ef4441",
      "--vui-table-cell-px": "calc(var(--spacing) * 3)",
      "--vui-table-cell-py": "calc(var(--spacing) * 3)",
      "--vui-table-cell-size": "var(--text-sm)",
      "--vui-table-cell-weight": "var(--font-weight-normal)",
      "--vui-table-cell-color": "var(--foreground)",
      "--vui-table-head-size": "var(--text-sm)",
      "--vui-table-head-weight": "var(--font-weight-semibold)",
      "--vui-table-head-color": "var(--muted-foreground)",
      "--vui-table-key-weight": "var(--font-weight-semibold)",
      "--vui-table-key-color": "var(--foreground)",
      "--vui-table-rule": "var(--border)",
      "--vui-nav-heading-size": "var(--text-xs)",
      "--vui-nav-heading-weight": "var(--font-weight-medium)",
      "--vui-nav-heading-tracking": "0.06em",
      "--vui-crumb-gap": "calc(var(--spacing) * 1)",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "var(--border-width)",
      "--vui-crumb-sep-size": "var(--text-lg)",
      "--vui-crumb-sep-opacity": "0.3",
      "--vui-search-w": "calc(var(--spacing) * 62)",
      "--vui-radius-xs": "calc(var(--radius) * 0.667)",
      "--vui-icon-muted": "var(--muted-foreground)",
      "--vui-logo-h": "calc(var(--spacing) * 7)",
      "--vui-icon-size": "calc(var(--text-sm) * var(--text-sm--line-height))",
      "--vui-shadow-xs": "0 0 1px 0 #adadad1a",
      "--vui-shadow-sm": "0 1px 1px 0 #adadad17",
      "--vui-shadow-md": "0 3px 2px 0 #adadad0d",
      "--vui-shadow-lg": "0 6px 2px 0 #adadad03",
      "--vui-shadow-xl": "0 9px 2px 0 #adadad03",
      "--shadow-1": "0 1px 1px 0 #adadad17",
      "--shadow-3": "0 3px 2px 0 #adadad0d",
      "--chart-1": "#4592ff",
      "--chart-2": "#d8bfff",
      "--chart-3": "#33664d",
      "--chart-4": "#ef4441",
      "--chart-5": "#8f8f8f",
      "--secondary": "#f2f4f7",
      "--secondary-foreground": "#4b5157",
      "--success-foreground": "#ffffff",
      "--warning-foreground": "oklch(0.985 0 0)",
      "--info-foreground": "oklch(0.985 0 0)",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#010101",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-ring": "#010101",
      "--vui-duration-fast": "0.1s",
      "--vui-duration-base": "0.15s",
      "--vui-duration-slow": "0.22s",
      "--vui-duration-ui": "0.1s",
      "--vui-ease": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-ui": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-panel": "cubic-bezier(0.2, 0, 0, 1)",
      "--font-scale": "0.94",
      "--text-caption": "12px",
      "--text-caption-leading": "1.25",
      "--text-lead": "var(--text-lead)",
      "--text-lead-leading": "1.6",
      "--text-h4": "var(--text-h4)",
      "--text-h4-leading": "1.35",
      "--text-h3": "var(--text-h3)",
      "--text-h3-leading": "1.25",
      "--text-h2": "var(--text-h2)",
      "--text-h2-leading": "1.2",
      "--text-h1": "var(--text-h1)",
      "--text-h1-leading": "1.15",
      "--text-display": "var(--text-display)",
      "--text-display-leading": "1.1",
      "--text-3xl": "1.5rem",
      "--vui-section-sm": "var(--vui-section-sm)",
      "--vui-section-md": "var(--vui-section-md)",
      "--vui-section-lg": "var(--vui-section-lg)",
      "--vui-section-xl": "var(--vui-section-xl)",
      "--vui-section-2xl": "var(--vui-section-2xl)",
      "--section-y": "clamp(3.5rem, 2rem + 5vw, 7rem)",
      "--section-y-tight": "clamp(2.5rem, 1.5rem + 3vw, 4.5rem)",
      "--brand-ink": "#010101",
      "--brand-mist": "#fafafa",
      "--brand-indigo": "#4592ff",
      "--brand-violet": "#d8bfff",
      "--brand-mint": "#33664d",
      "--brand-coral": "#ef4441",
      "--accent-violet": "#d8bfff",
      "--accent-pink": "#f3ebff",
      "--vui-file-badge-doc": "#e44b4d",
      "--vui-file-badge-doc-light": "#fbcfd0",
      "--vui-file-badge-doc-mid": "#cd4445",
      "--vui-file-badge-doc-shade": "#963232",
      "--vui-file-badge-sheet": "#6dbf39",
      "--vui-file-badge-sheet-light": "#dffacd",
      "--vui-file-badge-sheet-mid": "#589b2e",
      "--vui-file-badge-sheet-shade": "#4f8c29",
      "--vui-file-badge-ink": "#1a1a1a",
      "--vui-file-badge-paper": "#fff",
      "--vui-file-badge-raw": "red",
      "--vui-folder-badge": "#fbbc1a",
      "--vui-folder-badge-light": "#ffdc78",
      "--vui-tile-mark-box": "44px",
      "--vui-page-inset": "25px",
      "--vui-page-top-gap": "25px"
    },
    "frame": {
      "shell": "rackwise",
      "regions": [
        "account",
        "search",
        "sidebarNav",
        "sidebarFoot",
        "pageTitle",
        "utilities",
        "pageActions",
        "fab",
        "children"
      ],
      "brand": "account",
      "sidebarSearch": true,
      "navIcons": true,
      "expander": "chevron",
      "submenuRule": false,
      "headerEnd": "cta",
      "sidebarWidth": 195,
      "sidebarFill": "tinted",
      "headingCase": "sentence",
      "activeMark": "raised-pill",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "durara",
    "label": "Counter",
    "hint": "An eCommerce operations console: a wide tinted rail, a lime primary, the profile at the foot.",
    "tokens": {
      "--font-sans": "var(--font-inter-tight), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "var(--font-jetbrains-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "16px",
      "--text-body-leading": "25px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.18rem",
      "--radius": "6px",
      "--vui-radius-surface": "8px",
      "--border-width": "1px",
      "--vui-control-h": "40px",
      "--vui-control-h-sm": "32px",
      "--vui-header-h": "66px",
      "--vui-header-h-lg": "66px",
      "--background": "#ffffff",
      "--foreground": "#030712",
      "--card": "#ffffff",
      "--card-foreground": "#030712",
      "--popover": "#ffffff",
      "--popover-foreground": "#030712",
      "--muted": "#f9fafb",
      "--muted-foreground": "#6b7280",
      "--accent": "#ecfccb",
      "--accent-foreground": "#3f6212",
      "--border": "#e5e7eb",
      "--input": "#d1d5db",
      "--ring": "#84cc16",
      "--sidebar": "#f3f4f6",
      "--sidebar-foreground": "#030712",
      "--sidebar-border": "#e5e7eb",
      "--sidebar-accent": "#ffffff",
      "--vui-selected": "var(--accent)",
      "--vui-selected-foreground": "var(--accent-foreground)",
      "--sidebar-accent-foreground": "#030712",
      "--brand": "#84cc16",
      "--primary": "#84cc16",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#84cc16",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#65a30d",
      "--success": "#22c55e",
      "--warning": "#ca8a04",
      "--info": "#8b5cf6",
      "--destructive": "#dc2626",
      "--vui-table-cell-px": "calc(var(--spacing) * 3)",
      "--vui-table-cell-py": "calc(var(--spacing) * 3)",
      "--vui-table-cell-size": "var(--text-sm)",
      "--vui-table-cell-weight": "var(--font-weight-normal)",
      "--vui-table-cell-color": "var(--foreground)",
      "--vui-table-head-size": "var(--text-sm)",
      "--vui-table-head-weight": "var(--font-weight-semibold)",
      "--vui-table-head-color": "var(--muted-foreground)",
      "--vui-table-key-weight": "var(--font-weight-semibold)",
      "--vui-table-key-color": "var(--foreground)",
      "--vui-table-rule": "var(--border)",
      "--vui-nav-heading-size": "var(--text-xs)",
      "--vui-nav-heading-weight": "var(--font-weight-medium)",
      "--vui-nav-heading-tracking": "0.06em",
      "--vui-crumb-gap": "calc(var(--spacing) * 1)",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "var(--border-width)",
      "--vui-crumb-sep-size": "var(--text-lg)",
      "--vui-crumb-sep-opacity": "0.3",
      "--vui-search-w": "248px",
      "--vui-radius-xs": "calc(var(--radius) * 0.667)",
      "--vui-icon-muted": "var(--muted-foreground)",
      "--vui-logo-h": "28px",
      "--vui-icon-size": "calc(var(--text-sm) * var(--text-sm--line-height))",
      "--vui-shadow-xs": "0 0 1px 0 #0d0d1210",
      "--vui-shadow-sm": "0 1px 1px 0 #0d0d120d",
      "--vui-shadow-md": "0 1px 2px 0 #1018280f",
      "--vui-shadow-lg": "0 16px 32px -12px #07204540",
      "--vui-shadow-xl": "0 16px 32px -12px #07204540",
      "--shadow-1": "0 1px 2px 0 #1018280f",
      "--shadow-3": "0 16px 32px -12px #07204540",
      "--chart-1": "#84cc16",
      "--chart-2": "#8b5cf6",
      "--chart-3": "#22c55e",
      "--chart-4": "#ca8a04",
      "--chart-5": "#dc2626",
      "--secondary": "#f3f4f6",
      "--secondary-foreground": "#3f3f46",
      "--success-foreground": "#ffffff",
      "--warning-foreground": "#ffffff",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#84cc16",
      "--sidebar-primary-foreground": "#030712",
      "--sidebar-ring": "#84cc16",
      "--vui-duration-fast": "0.1s",
      "--vui-duration-base": "0.15s",
      "--vui-duration-slow": "0.22s",
      "--vui-duration-ui": "0.1s",
      "--vui-ease": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-ui": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-panel": "cubic-bezier(0.2, 0, 0, 1)",
      "--font-scale": "1",
      "--text-caption": "12px",
      "--text-caption-leading": "1.583",
      "--text-lead": "18px",
      "--text-lead-leading": "1.556",
      "--text-h4": "20px",
      "--text-h4-leading": "1.4",
      "--text-h3": "24px",
      "--text-h3-leading": "1.5",
      "--text-h2": "32px",
      "--text-h2-leading": "1.406",
      "--text-h1": "40px",
      "--text-h1-leading": "1.2",
      "--text-display": "48px",
      "--text-display-leading": "1.25",
      "--text-3xl": "24px",
      "--vui-section-sm": "var(--vui-section-sm)",
      "--vui-section-md": "var(--vui-section-md)",
      "--vui-section-lg": "var(--vui-section-lg)",
      "--vui-section-xl": "var(--vui-section-xl)",
      "--vui-section-2xl": "var(--vui-section-2xl)",
      "--section-y": "clamp(3.5rem, 2rem + 5vw, 7rem)",
      "--section-y-tight": "clamp(2.5rem, 1.5rem + 3vw, 4.5rem)",
      "--brand-ink": "#030712",
      "--brand-mist": "#f9fafb",
      "--brand-indigo": "#8b5cf6",
      "--brand-violet": "#7c3aed",
      "--brand-mint": "#22c55e",
      "--brand-coral": "#dc2626",
      "--accent-violet": "#8b5cf6",
      "--accent-pink": "#c4b5fd",
      "--vui-file-badge-doc": "#e44b4d",
      "--vui-file-badge-doc-light": "#fbcfd0",
      "--vui-file-badge-doc-mid": "#cd4445",
      "--vui-file-badge-doc-shade": "#963232",
      "--vui-file-badge-sheet": "#6dbf39",
      "--vui-file-badge-sheet-light": "#dffacd",
      "--vui-file-badge-sheet-mid": "#589b2e",
      "--vui-file-badge-sheet-shade": "#4f8c29",
      "--vui-file-badge-ink": "#1a1a1a",
      "--vui-file-badge-paper": "#fff",
      "--vui-file-badge-raw": "red",
      "--vui-folder-badge": "#fbbc1a",
      "--vui-folder-badge-light": "#ffdc78",
      "--vui-tile-mark-box": "44px",
      "--vui-page-inset": "25px",
      "--vui-page-top-gap": "12px"
    },
    "frame": {
      "shell": "durara",
      "regions": [
        "identity",
        "contextSwitch",
        "search",
        "sidebarNav",
        "account",
        "pageTitle",
        "pageActions",
        "banner",
        "fab",
        "children"
      ],
      "brand": "wordmark",
      "sidebarSearch": true,
      "navIcons": true,
      "expander": "chevron",
      "submenuRule": false,
      "headerEnd": "cta",
      "sidebarWidth": 272,
      "sidebarFill": "tinted",
      "headingCase": "sentence",
      "activeMark": "raised-pill",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "swift",
    "label": "Panel",
    "hint": "A friendly SaaS console: a white rail on a grey page, indigo actions, no header band.",
    "tokens": {
      "--font-sans": "var(--font-nunito), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "var(--font-jetbrains-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "12px",
      "--text-body-leading": "16px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.18rem",
      "--radius": "5px",
      "--vui-radius-surface": "10px",
      "--border-width": "2px",
      "--vui-control-h": "34px",
      "--vui-control-h-sm": "28px",
      "--vui-header-h": "62px",
      "--vui-header-h-lg": "66px",
      "--background": "#fafafb",
      "--foreground": "#030229",
      "--card": "#ffffff",
      "--card-foreground": "#030229",
      "--popover": "#ffffff",
      "--popover-foreground": "#030229",
      "--muted": "#f7f7f8",
      "--muted-foreground": "#7a7a9d",
      "--accent": "#ececff",
      "--accent-foreground": "#605bff",
      "--border": "color-mix(in oklab, var(--foreground) 16%, var(--background))",
      "--input": "color-mix(in oklab, var(--foreground) 26%, var(--background))",
      "--ring": "#605bff",
      "--sidebar": "#ffffff",
      "--sidebar-foreground": "#030229",
      "--sidebar-border": "#f0f0f4",
      "--sidebar-accent": "#ececff",
      "--vui-selected": "var(--accent)",
      "--vui-selected-foreground": "var(--accent-foreground)",
      "--sidebar-accent-foreground": "#605bff",
      "--brand": "#605bff",
      "--primary": "#605bff",
      "--primary-foreground": "#ffffff",
      "--button-primary": "#605bff",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#5049e0",
      "--success": "#039855",
      "--warning": "#ffd66b",
      "--info": "#26c0e2",
      "--destructive": "#ff8f6b",
      "--vui-table-cell-px": "calc(var(--spacing) * 3)",
      "--vui-table-cell-py": "calc(var(--spacing) * 3)",
      "--vui-table-cell-size": "var(--text-sm)",
      "--vui-table-cell-weight": "var(--font-weight-normal)",
      "--vui-table-cell-color": "var(--foreground)",
      "--vui-table-head-size": "var(--text-sm)",
      "--vui-table-head-weight": "var(--font-weight-semibold)",
      "--vui-table-head-color": "var(--muted-foreground)",
      "--vui-table-key-weight": "var(--font-weight-semibold)",
      "--vui-table-key-color": "var(--foreground)",
      "--vui-table-rule": "var(--border)",
      "--vui-nav-heading-size": "var(--text-xs)",
      "--vui-nav-heading-weight": "var(--font-weight-medium)",
      "--vui-nav-heading-tracking": "0.06em",
      "--vui-crumb-gap": "calc(var(--spacing) * 1)",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "var(--border-width)",
      "--vui-crumb-sep-size": "var(--text-lg)",
      "--vui-crumb-sep-opacity": "0.3",
      "--vui-search-w": "calc(var(--spacing) * 62)",
      "--vui-radius-xs": "calc(var(--radius) * 0.667)",
      "--vui-icon-muted": "var(--muted-foreground)",
      "--vui-logo-h": "calc(var(--spacing) * 7)",
      "--vui-icon-size": "calc(var(--text-sm) * var(--text-sm--line-height))",
      "--vui-shadow-xs": "0 4px 7px 0 #03022912",
      "--vui-shadow-sm": "0 4px 7px 0 #03022912",
      "--vui-shadow-md": "0 4px 4px 0 #605bff2b",
      "--vui-shadow-lg": "0 4px 4px 0 #5b93ff3d",
      "--vui-shadow-xl": "0 4px 4px 0 #5b93ff3d",
      "--shadow-1": "0 4px 7px 0 #03022912",
      "--shadow-3": "0 4px 4px 0 #605bff2b",
      "--chart-1": "#5b93ff",
      "--chart-2": "#605bff",
      "--chart-3": "#ffd66b",
      "--chart-4": "#ff8f6b",
      "--chart-5": "#26c0e2",
      "--secondary": "#f7f7f8",
      "--secondary-foreground": "#030229",
      "--success-foreground": "oklch(0.985 0 0)",
      "--warning-foreground": "#030229",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#605bff",
      "--sidebar-primary-foreground": "#ffffff",
      "--sidebar-ring": "#605bff",
      "--vui-duration-fast": "0.1s",
      "--vui-duration-base": "0.15s",
      "--vui-duration-slow": "0.22s",
      "--vui-duration-ui": "0.1s",
      "--vui-ease": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-ui": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-panel": "cubic-bezier(0.2, 0, 0, 1)",
      "--font-scale": "0.94",
      "--text-caption": "12px",
      "--text-caption-leading": "1.333",
      "--text-lead": "var(--text-lead)",
      "--text-lead-leading": "1.6",
      "--text-h4": "16px",
      "--text-h4-leading": "1.35",
      "--text-h3": "18px",
      "--text-h3-leading": "1.25",
      "--text-h2": "22px",
      "--text-h2-leading": "1.2",
      "--text-h1": "var(--text-h1)",
      "--text-h1-leading": "1.15",
      "--text-display": "var(--text-display)",
      "--text-display-leading": "1.1",
      "--text-3xl": "1.5rem",
      "--vui-section-sm": "var(--vui-section-sm)",
      "--vui-section-md": "var(--vui-section-md)",
      "--vui-section-lg": "var(--vui-section-lg)",
      "--vui-section-xl": "var(--vui-section-xl)",
      "--vui-section-2xl": "var(--vui-section-2xl)",
      "--section-y": "clamp(3.5rem, 2rem + 5vw, 7rem)",
      "--section-y-tight": "clamp(2.5rem, 1.5rem + 3vw, 4.5rem)",
      "--brand-ink": "#030229",
      "--brand-mist": "#fafafb",
      "--brand-indigo": "#605bff",
      "--brand-violet": "#5b93ff",
      "--brand-mint": "#26c0e2",
      "--brand-coral": "#ff8f6b",
      "--accent-violet": "#605bff",
      "--accent-pink": "#ff8f6b",
      "--vui-file-badge-doc": "#e44b4d",
      "--vui-file-badge-doc-light": "#fbcfd0",
      "--vui-file-badge-doc-mid": "#cd4445",
      "--vui-file-badge-doc-shade": "#963232",
      "--vui-file-badge-sheet": "#6dbf39",
      "--vui-file-badge-sheet-light": "#dffacd",
      "--vui-file-badge-sheet-mid": "#589b2e",
      "--vui-file-badge-sheet-shade": "#4f8c29",
      "--vui-file-badge-ink": "#1a1a1a",
      "--vui-file-badge-paper": "#fff",
      "--vui-file-badge-raw": "red",
      "--vui-folder-badge": "#fbbc1a",
      "--vui-folder-badge-light": "#ffdc78",
      "--vui-tile-mark-box": "44px",
      "--vui-page-inset": "25px",
      "--vui-page-top-gap": "25px"
    },
    "frame": {
      "shell": "swift",
      "regions": [
        "identity",
        "sidebarNav",
        "sidebarFoot",
        "children"
      ],
      "brand": "wordmark",
      "sidebarSearch": false,
      "navIcons": true,
      "expander": "none",
      "submenuRule": false,
      "sidebarWidth": 218,
      "sidebarFill": "none",
      "headingCase": "sentence",
      "activeMark": "bar-tint",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "flow",
    "label": "Flow",
    "hint": "Three floating cards on a grey ground: a violet AI console with a rounded, gutter-inset chrome.",
    "tokens": {
      "--font-sans": "var(--font-archivo), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "var(--font-jetbrains-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "16px",
      "--text-body-leading": "24px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.18rem",
      "--radius": "8px",
      "--vui-radius-surface": "20px",
      "--border-width": "2px",
      "--vui-control-h": "48px",
      "--vui-control-h-sm": "28px",
      "--vui-header-h": "76px",
      "--vui-header-h-lg": "66px",
      "--background": "#F7F7F8",
      "--foreground": "#1A2526",
      "--card": "#FFFFFF",
      "--card-foreground": "#1A2526",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#1A2526",
      "--muted": "#f7f7f8",
      "--muted-foreground": "#606C65",
      "--accent": "#F5EDFF",
      "--accent-foreground": "#9D47FF",
      "--border": "#E1E6E7",
      "--input": "#E1E6E7",
      "--ring": "#9D47FF",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#1A2526",
      "--sidebar-border": "#f0f0f4",
      "--sidebar-accent": "#F7F7F8",
      "--vui-selected": "var(--accent)",
      "--vui-selected-foreground": "var(--accent-foreground)",
      "--sidebar-accent-foreground": "#1A2526",
      "--brand": "#9D47FF",
      "--primary": "#9D47FF",
      "--primary-foreground": "#FFFFFF",
      "--button-primary": "#9D47FF",
      "--button-primary-foreground": "#ffffff",
      "--button-primary-hover": "#8F41E8",
      "--success": "#34919B",
      "--warning": "#FFC84C",
      "--info": "#9D47FF",
      "--destructive": "#DE4400",
      "--vui-table-cell-px": "calc(var(--spacing) * 3)",
      "--vui-table-cell-py": "calc(var(--spacing) * 3)",
      "--vui-table-cell-size": "var(--text-sm)",
      "--vui-table-cell-weight": "var(--font-weight-normal)",
      "--vui-table-cell-color": "var(--foreground)",
      "--vui-table-head-size": "var(--text-sm)",
      "--vui-table-head-weight": "var(--font-weight-semibold)",
      "--vui-table-head-color": "var(--muted-foreground)",
      "--vui-table-key-weight": "var(--font-weight-semibold)",
      "--vui-table-key-color": "var(--foreground)",
      "--vui-table-rule": "var(--border)",
      "--vui-nav-heading-size": "var(--text-xs)",
      "--vui-nav-heading-weight": "var(--font-weight-medium)",
      "--vui-nav-heading-tracking": "0.06em",
      "--vui-crumb-gap": "calc(var(--spacing) * 1)",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "var(--border-width)",
      "--vui-crumb-sep-size": "var(--text-lg)",
      "--vui-crumb-sep-opacity": "0.3",
      "--vui-search-w": "calc(var(--spacing) * 62)",
      "--vui-radius-xs": "4px",
      "--vui-icon-muted": "var(--muted-foreground)",
      "--vui-logo-h": "calc(var(--spacing) * 7)",
      "--vui-icon-size": "calc(var(--text-sm) * var(--text-sm--line-height))",
      "--vui-shadow-xs": "0 4px 7px 0 #03022912",
      "--vui-shadow-sm": "0 4px 7px 0 #03022912",
      "--vui-shadow-md": "0 4px 4px 0 #605bff2b",
      "--vui-shadow-lg": "0 4px 4px 0 #5b93ff3d",
      "--vui-shadow-xl": "0 4px 4px 0 #5b93ff3d",
      "--shadow-1": "0 4px 7px 0 #03022912",
      "--shadow-3": "0 4px 4px 0 #605bff2b",
      "--chart-1": "#9D47FF",
      "--chart-2": "#34919B",
      "--chart-3": "#FFC84C",
      "--chart-4": "#DE4400",
      "--chart-5": "#BD84FF",
      "--secondary": "#f7f7f8",
      "--secondary-foreground": "#1A2526",
      "--success-foreground": "oklch(0.985 0 0)",
      "--warning-foreground": "#030229",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#9D47FF",
      "--sidebar-primary-foreground": "#FFFFFF",
      "--sidebar-ring": "#9D47FF",
      "--vui-duration-fast": "0.1s",
      "--vui-duration-base": "0.15s",
      "--vui-duration-slow": "0.22s",
      "--vui-duration-ui": "0.1s",
      "--vui-ease": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-ui": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-panel": "cubic-bezier(0.2, 0, 0, 1)",
      "--font-scale": "1",
      "--text-caption": "12px",
      "--text-caption-leading": "16px",
      "--text-lead": "24px",
      "--text-lead-leading": "32px",
      "--text-h4": "32px",
      "--text-h4-leading": "40px",
      "--text-h3": "40px",
      "--text-h3-leading": "48px",
      "--text-h2": "48px",
      "--text-h2-leading": "56px",
      "--text-h1": "56px",
      "--text-h1-leading": "64px",
      "--text-display": "var(--text-display)",
      "--text-display-leading": "1.1",
      "--text-3xl": "1.5rem",
      "--vui-section-sm": "var(--vui-section-sm)",
      "--vui-section-md": "var(--vui-section-md)",
      "--vui-section-lg": "var(--vui-section-lg)",
      "--vui-section-xl": "var(--vui-section-xl)",
      "--vui-section-2xl": "var(--vui-section-2xl)",
      "--section-y": "clamp(3.5rem, 2rem + 5vw, 7rem)",
      "--section-y-tight": "clamp(2.5rem, 1.5rem + 3vw, 4.5rem)",
      "--brand-ink": "#030229",
      "--brand-mist": "#fafafb",
      "--brand-indigo": "#605bff",
      "--brand-violet": "#5b93ff",
      "--brand-mint": "#26c0e2",
      "--brand-coral": "#ff8f6b",
      "--accent-violet": "#605bff",
      "--accent-pink": "#ff8f6b",
      "--vui-file-badge-doc": "#e44b4d",
      "--vui-file-badge-doc-light": "#fbcfd0",
      "--vui-file-badge-doc-mid": "#cd4445",
      "--vui-file-badge-doc-shade": "#963232",
      "--vui-file-badge-sheet": "#6dbf39",
      "--vui-file-badge-sheet-light": "#dffacd",
      "--vui-file-badge-sheet-mid": "#589b2e",
      "--vui-file-badge-sheet-shade": "#4f8c29",
      "--vui-file-badge-ink": "#1a1a1a",
      "--vui-file-badge-paper": "#fff",
      "--vui-file-badge-raw": "red",
      "--vui-folder-badge": "#fbbc1a",
      "--vui-folder-badge-light": "#ffdc78",
      "--vui-tile-mark-box": "44px",
      "--vui-page-inset": "25px",
      "--vui-page-top-gap": "25px"
    },
    "frame": {
      "shell": "flow",
      "regions": [
        "identity",
        "search",
        "account",
        "utilities",
        "sidebarTop",
        "sidebarNav",
        "sidebarFoot",
        "pageTitle",
        "pageDescription",
        "children"
      ],
      "brand": "wordmark",
      "sidebarSearch": false,
      "navIcons": true,
      "expander": "chevron",
      "submenuRule": false,
      "headerEnd": "account",
      "sidebarWidth": 272,
      "sidebarFill": "none",
      "headingCase": "uppercase",
      "activeMark": "flat-tint",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "tendora",
    "label": "Reach",
    "hint": "An edge-to-edge rail flush to the viewport in rose and Inter Tight, with a rail search and a page-toolbar band under the header.",
    "tokens": {
      "--font-sans": "var(--font-inter-tight), ui-sans-serif, system-ui, sans-serif",
      "--font-mono": "var(--font-jetbrains-mono), ui-monospace, SFMono-Regular, Menlo, monospace",
      "--text-xs": "12px",
      "--text-sm": "14px",
      "--text-base": "16px",
      "--text-body": "14px",
      "--text-body-leading": "21px",
      "--font-weight-normal": "400",
      "--font-weight-medium": "500",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--spacing": "0.25rem",
      "--radius": "10px",
      "--vui-radius-surface": "16px",
      "--border-width": "1px",
      "--vui-control-h": "40px",
      "--vui-control-h-sm": "28px",
      "--vui-header-h": "72px",
      "--vui-header-h-lg": "66px",
      "--background": "#FFFFFF",
      "--foreground": "#0D0D12",
      "--card": "#FFFFFF",
      "--card-foreground": "#0D0D12",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#0D0D12",
      "--muted": "#F6F8FA",
      "--muted-foreground": "#666D80",
      "--accent": "#FCE8EE",
      "--accent-foreground": "#DE1A58",
      "--border": "#DFE1E7",
      "--input": "#DFE1E7",
      "--ring": "#DE1A58",
      "--sidebar": "#FFFFFF",
      "--sidebar-foreground": "#36394A",
      "--sidebar-border": "#ECEFF3",
      "--sidebar-accent": "#FCE8EE",
      "--vui-selected": "var(--accent)",
      "--vui-selected-foreground": "var(--accent-foreground)",
      "--sidebar-accent-foreground": "#DE1A58",
      "--brand": "#DE1A58",
      "--primary": "#DE1A58",
      "--primary-foreground": "#FFFFFF",
      "--button-primary": "#DE1A58",
      "--button-primary-foreground": "#FFFFFF",
      "--button-primary-hover": "#E54879",
      "--success": "#40C4AA",
      "--warning": "#FFBE4C",
      "--info": "#33CFFF",
      "--destructive": "#DF1C41",
      "--vui-table-cell-px": "calc(var(--spacing) * 3)",
      "--vui-table-cell-py": "calc(var(--spacing) * 3)",
      "--vui-table-cell-size": "var(--text-sm)",
      "--vui-table-cell-weight": "var(--font-weight-normal)",
      "--vui-table-cell-color": "var(--foreground)",
      "--vui-table-head-size": "var(--text-sm)",
      "--vui-table-head-weight": "var(--font-weight-semibold)",
      "--vui-table-head-color": "var(--muted-foreground)",
      "--vui-table-key-weight": "var(--font-weight-semibold)",
      "--vui-table-key-color": "var(--foreground)",
      "--vui-table-rule": "var(--border)",
      "--vui-nav-heading-size": "var(--text-xs)",
      "--vui-nav-heading-weight": "var(--font-weight-medium)",
      "--vui-nav-heading-tracking": "0.06em",
      "--vui-crumb-gap": "calc(var(--spacing) * 1)",
      "--vui-crumb-sep-weight": "400",
      "--vui-nav-rule-w": "var(--border-width)",
      "--vui-crumb-sep-size": "var(--text-lg)",
      "--vui-crumb-sep-opacity": "0.3",
      "--vui-search-w": "calc(var(--spacing) * 62)",
      "--vui-radius-xs": "8px",
      "--vui-icon-muted": "var(--muted-foreground)",
      "--vui-logo-h": "calc(var(--spacing) * 7)",
      "--vui-icon-size": "calc(var(--text-sm) * var(--text-sm--line-height))",
      "--vui-shadow-xs": "0 4px 7px 0 #03022912",
      "--vui-shadow-sm": "0 4px 7px 0 #03022912",
      "--vui-shadow-md": "0 4px 4px 0 #0D0D121a",
      "--vui-shadow-lg": "0 8px 24px 0 #0D0D1226",
      "--vui-shadow-xl": "0 16px 40px 0 #0D0D1226",
      "--shadow-1": "0 4px 7px 0 #03022912",
      "--shadow-3": "0 4px 4px 0 #0D0D121a",
      "--chart-1": "#DE1A58",
      "--chart-2": "#33CFFF",
      "--chart-3": "#40C4AA",
      "--chart-4": "#FFBE4C",
      "--chart-5": "#E9668F",
      "--secondary": "#f7f7f8",
      "--secondary-foreground": "#36394A",
      "--success-foreground": "oklch(0.985 0 0)",
      "--warning-foreground": "#0D0D12",
      "--info-foreground": "#ffffff",
      "--destructive-foreground": "#ffffff",
      "--sidebar-primary": "#DE1A58",
      "--sidebar-primary-foreground": "#FFFFFF",
      "--sidebar-ring": "#DE1A58",
      "--vui-duration-fast": "0.1s",
      "--vui-duration-base": "0.15s",
      "--vui-duration-slow": "0.22s",
      "--vui-duration-ui": "0.1s",
      "--vui-ease": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-ui": "cubic-bezier(0.2, 0, 0, 1)",
      "--vui-ease-panel": "cubic-bezier(0.2, 0, 0, 1)",
      "--font-scale": "1",
      "--text-caption": "12px",
      "--text-caption-leading": "18px",
      "--text-lead": "20px",
      "--text-lead-leading": "27px",
      "--text-h5": "20px",
      "--text-h4": "24px",
      "--text-h4-leading": "31px",
      "--text-h3": "32px",
      "--text-h3-leading": "40px",
      "--text-h2": "48px",
      "--text-h2-leading": "58px",
      "--text-h1": "64px",
      "--text-h1-leading": "80px",
      "--text-display-leading": "1.1",
      "--text-3xl": "1.5rem",
      "--section-y": "clamp(3.5rem, 2rem + 5vw, 7rem)",
      "--section-y-tight": "clamp(2.5rem, 1.5rem + 3vw, 4.5rem)",
      "--brand-ink": "#0D0D12",
      "--brand-mist": "#F8FAFB",
      "--brand-indigo": "#DE1A58",
      "--brand-violet": "#E9668F",
      "--brand-mint": "#40C4AA",
      "--brand-coral": "#FFBE4C",
      "--accent-violet": "#DE1A58",
      "--accent-pink": "#E9668F",
      "--vui-file-badge-doc": "#e44b4d",
      "--vui-file-badge-doc-light": "#fbcfd0",
      "--vui-file-badge-doc-mid": "#cd4445",
      "--vui-file-badge-doc-shade": "#963232",
      "--vui-file-badge-sheet": "#6dbf39",
      "--vui-file-badge-sheet-light": "#dffacd",
      "--vui-file-badge-sheet-mid": "#589b2e",
      "--vui-file-badge-sheet-shade": "#4f8c29",
      "--vui-file-badge-ink": "#1a1a1a",
      "--vui-file-badge-paper": "#fff",
      "--vui-file-badge-raw": "red",
      "--vui-folder-badge": "#fbbc1a",
      "--vui-folder-badge-light": "#ffdc78",
      "--vui-tile-mark-box": "44px",
      "--vui-page-inset": "24px",
      "--vui-page-top-gap": "20px",
      "--vui-card-gap": "20px"
    },
    "frame": {
      "shell": "tendora",
      "regions": [
        "quickActions",
        "identity",
        "search",
        "sidebarNav",
        "sidebarFoot",
        "account",
        "utilities",
        "pageTitle",
        "pageToolbar",
        "children"
      ],
      "brand": "wordmark",
      "sidebarSearch": true,
      "navIcons": true,
      "expander": "chevron",
      "submenuRule": false,
      "headerEnd": "account",
      "sidebarWidth": 272,
      "sidebarFill": "none",
      "headingCase": "uppercase",
      "activeMark": "flat-tint",
      "contentMaxWidth": 0
    }
  },
  {
    "id": "sales-force",
    "label": "Cloud",
    "hint": "An enterprise cloud console: two stacked header rows, a navigation that swaps between a row and a rail, and a docked panel.",
    "tokens": {
      "--radius": "8px",
      "--text-xs": "12px",
      "--font-weight-semibold": "600",
      "--font-weight-bold": "700",
      "--background": "#F3F3F3",
      "--foreground": "#2E2E2E",
      "--card": "#FFFFFF",
      "--card-foreground": "#2E2E2E",
      "--popover": "#FFFFFF",
      "--popover-foreground": "#2E2E2E",
      "--muted": "#F3F3F3",
      "--muted-foreground": "#747474",
      "--border": "#C9C9C9",
      "--input": "#C9C9C9",
      "--primary": "#0176D3",
      "--primary-foreground": "#FFFFFF",
      "--brand": "#0176D3",
      "--button-primary": "#0176D3",
      "--button-primary-foreground": "#FFFFFF",
      "--ring": "#0176D3",
      "--accent-foreground": "#0176D3",
      "--sidebar": "#E5E5E5",
      "--sidebar-foreground": "#2E2E2E",
      "--sidebar-border": "#C9C9C9"
    },
    "frame": {
      "shell": "sales-force",
      "regions": [
        "identity",
        "apps",
        "search",
        "utilities",
        "account",
        "primaryNav",
        "sidebarNav",
        "contextSwitch",
        "pageHeader",
        "breadcrumb",
        "children",
        "aside"
      ],
      "brand": "wordmark",
      "sidebarSearch": false,
      "navIcons": true,
      "expander": "none",
      "submenuRule": false,
      "sidebarWidth": 78,
      "sidebarFill": "tinted",
      "headingCase": "uppercase",
      "activeMark": "flat-tint",
      "contentMaxWidth": 0
    }
  }
] as const;
